# Generated by Django 4.0.3 on 2022-04-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='bank',
            field=models.OneToOneField(blank=True, db_column='bank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='banks.bank'),
        ),
    ]
